# Generated by Django 6.0.5 on 2026-06-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('location', models.CharField(max_length=150, verbose_name='Локация')),
                ('event_date', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('max_guests', models.IntegerField(verbose_name='Максимальное количество гостей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
