# Generated by Django 6.0.5 on 2026-06-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
