# Generated by Django 6.0.5 on 2026-06-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stock',
        ),
    ]
